services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "false"
      KC_LOG_LEVEL: info
    volumes:
      - ./Keycloak/keycloak-data.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--http-port", "7080", "--import-realm"]
    ports:
      - "7080:7080"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge