services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "false"
      KC_LOG_LEVEL: info
    volumes:
      - ./Keycloak/keycloak-data.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--http-port", "7080", "--import-realm"]
    ports:
      - "7080:7080"
    networks:
      - local_network
  web:
    depends_on:
      - keycloak
    build:
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWT_AUTHORITY=http://keycloak:7080/realms/account-service
    networks:
      - local_network
networks:
  local_network:
    driver: bridge