services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "false"
      KC_LOG_LEVEL: info
    volumes:
      - ./Keycloak/keycloak-data.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--http-port", "7080", "--import-realm"]
    ports:
      - "7080:7080"
    networks:
      - local_network
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postus
      PGUSER: postus
      POSTGRES_PASSWORD: passus
      POSTGRES_DB: account_service_db
      PGDATA: /data/postgres
    ports:
      - "1234:5432"
    volumes:
      - db:/data/postgres
    networks:
      - local_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postus", "-d", "account_service_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq:
    depends_on:
      db:
        condition: service_healthy
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - local_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 20s
      retries: 5
  web:
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      dockerfile: Account Service/Dockerfile
    ports:
      - "0.0.0.0:80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWT_AUTHORITY=http://keycloak:7080/realms/account-service
      - DbSettings__ConnectionString=Host=db;Port=5432;Database=account_service_db;Username=postus;Password=passus
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  db:
  rabbitmq: